setup_infection:
	rm -rf ~/infection
	bash -c 'mkdir -p ~/infection/{one,two/{bla/{important,documents},deep},three/{haha/hoho}}'
	echo hi1 > ~/infection/docs.docs
	echo hi2 > ~/infection/docs2.png
	echo hi3 > ~/infection/docs3.blablanotme
	echo hi4 > ~/infection/docs4.xlsx
	echo important > ~/infection/two/bla/documents/homework_due_tomorrow.zip
	echo picpicpic > ~/infection/two/bla/documents/pictures_of_birthday.jpg
